import streamlit as st
import time
from agent import TicTacToeAgent

# Inject custom CSS for better responsiveness and centering
st.markdown("""
<style>
/* General app styling */
.reportview-container .main {
    display: flex;
    flex-direction: column;
    align-items: center; /* Center the entire app content */
    padding-top: 1rem;
}

/* Ensure the columns generated by Streamlit are always side-by-side */
/* This targets the div that Streamlit creates for st.columns */
div[data-testid="stHorizontalBlock"] {
    display: flex;
    flex-direction: row; /* Ensure they are rows, not stacked */
    justify-content: center; /* Center the whole row of columns */
    align-items: center;
    width: 100%; /* Take full available width */
    max-width: 300px; /* Limit overall board width for very large screens if desired, adjust */
}

/* Specific styling for the game cells (buttons and markdown divs) */
/* The width and height are critical for fitting 3 in a row */
.stButton>button, .tic-tac-toe-cell {
    /* Use calc() to dynamically size cells based on available column width */
    /* (100% of column width - total horizontal gap for 2 gaps) / 3 cells */
    width: calc(33.33% - 4px) !important; /* Approximately 1/3 minus some padding/margin */
    height: 80px !important; /* Keep height fixed, or make it dynamic as well */
    font-size: 40px !important;
    font-weight: bold;
    color: inherit; /* Inherit color from parent markdown for filled cells */
    text-align: center;
    line-height: 80px !important;
    padding: 0 !important;
    margin: 2px !important; /* Small margin between cells */
    border-radius: 5px; /* Slightly rounded corners */
    display: flex; /* Use flexbox for centering content within cell */
    justify-content: center;
    align-items: center;
    box-sizing: border-box; /* Include padding and border in the element's total width and height */
}

/* Adjust button specific styles */
.stButton>button {
    background-color: #f0f2f6; /* Streamlit's default button background */
    border: 1px solid #ccc; /* Add a border for empty cells */
    cursor: pointer;
}

/* Styles for filled cells to ensure they match button dimensions */
.tic-tac-toe-cell {
    border: 1px solid transparent; /* Mimic button border for alignment */
    background-color: transparent;
    user-select: none;
}

/* Media query for smaller mobile devices (e.g., iPhone SE, older iPhones) */
@media (max-width: 400px) {
    div[data-testid="stHorizontalBlock"] {
        max-width: 270px; /* Reduce max width of the board on smaller screens */
    }
    .stButton>button, .tic-tac-toe-cell {
        height: 70px !important;
        font-size: 36px !important;
        line-height: 70px !important;
    }
}

/* Even smaller devices */
@media (max-width: 320px) {
    div[data-testid="stHorizontalBlock"] {
        max-width: 240px; /* Further reduce max width */
    }
    .stButton>button, .tic-tac-toe-cell {
        height: 60px !important;
        font-size: 32px !important;
        line-height: 60px !important;
    }
}

</style>
""", unsafe_allow_html=True)


st.title("Tic Tac Toe with AI master 🤖")
st.markdown("""
You are <span style="color:blue;">**O**</span> and AI master is <span style="color:red;">**X**</span>.<br>
You always start first. Click once to place your O.<br>
AI will respond within 1 second.
""", unsafe_allow_html=True)

# Initialize session state for game statistics if not already present
if "board" not in st.session_state:
    st.session_state.board = [" "] * 9
    # Ensure TicTacToeAgent is defined or imported correctly
    # You will need to have your 'agent.py' file and 'agent_q_values_X.json'
    # in the same directory as your Streamlit app for this to work.
    try:
        st.session_state.agent = TicTacToeAgent("X", q_value_file="agent_q_values_X.json", epsilon=0.0)
    except FileNotFoundError:
        st.error("Error: 'agent_q_values_X.json' not found. Please ensure the AI Q-value file is in the same directory.")
        st.stop() # Stop the app if the agent file isn't found
    except Exception as e:
        st.error(f"Error initializing AI agent: {e}. Make sure agent.py is correctly defined.")
        st.stop()

    st.session_state.turn = "O"
    st.session_state.total_games = 0
    st.session_state.user_wins = 0
    st.session_state.ai_wins = 0
    st.session_state.draws = 0
    st.session_state.game_outcome_recorded = False

board = st.session_state.board
agent = st.session_state.agent

# Helper function to check if the game is over
def game_over(board):
    wins = [(0,1,2), (3,4,5), (6,7,8),
            (0,3,6), (1,4,7), (2,5,8),
            (0,4,8), (2,4,6)]
    for a, b, c in wins:
        if board[a] == board[b] == board[c] and board[a] != " ":
            return True # There's a winner
    return " " not in board # It's a draw if no winner and no empty spaces

def play_move(pos):
    if board[pos] == " " and st.session_state.turn == "O" and not game_over(board):
        board[pos] = "O"
        if not game_over(board):
            st.session_state.turn = "X"
        st.rerun()

def winner(board):
    wins = [(0,1,2), (3,4,5), (6,7,8),
            (0,3,6), (1,4,7), (2,5,8),
            (0,4,8), (2,4,6)]
    for a, b, c in wins:
        if board[a] == board[b] == board[c] and board[a] != " ":
            return board[a]
    return None

def print_board(board):
    is_game_finished = game_over(board)

    # We don't need an extra container here, Streamlit's columns are already in a container
    for i in range(3):
        # Using a fixed width column for the board itself to prevent it from stretching too wide on desktop
        # and to help center it, while letting the *cells* themselves be responsive inside.
        # This is often wrapped in st.container() but st.columns will do if sized properly
        cols = st.columns(3, gap="small")
        for j in range(3):
            idx = 3*i + j
            with cols[j]:
                symbol = board[idx]
                if symbol == " ":
                    clicked = st.button(
                        " ",
                        key=f"btn_{idx}",
                        help=f"Click to place O",
                        disabled=is_game_finished
                    )
                    if clicked:
                        play_move(idx)
                else:
                    color = "#FF4B4B" if symbol == "X" else "#4B9CFF"
                    st.markdown(f"""
                        <div class="tic-tac-toe-cell" style="color: {color};">
                            {symbol}
                        </div>
                    """, unsafe_allow_html=True)

print_board(board)

# AI's turn
if not game_over(board) and st.session_state.turn == "X":
    time.sleep(1)
    move = agent.select_move(board)
    if move is not None and board[move] == " ":
        board[move] = "X"
        if not game_over(board):
            st.session_state.turn = "O"
        st.rerun()
    else:
        st.error("AI could not make a valid move. This shouldn't happen.")
        st.session_state.turn = "O"


# --- Game Over Logic ---
if game_over(board):
    if st.session_state.get('game_outcome_recorded', False) == False:
        st.session_state.total_games += 1
        w = winner(board)
        if w == "O":
            st.session_state.user_wins += 1
        elif w == "X":
            st.session_state.ai_wins += 1
        else:
            st.session_state.draws += 1
        st.session_state.game_outcome_recorded = True

    w = winner(board)
    if w == "O":
        st.success("You win! 🎉")
    elif w == "X":
        st.error("AI Master wins! 😈")
    else:
        st.info("It's a draw! 🤝")

    if st.button("Play Again"):
        st.session_state.board = [" "] * 9
        st.session_state.turn = "O"
        st.session_state.game_outcome_recorded = False
        st.rerun()

# --- Display Statistics ---
st.markdown("---")
st.subheader("Game Statistics")

total = st.session_state.total_games
user_win_rate = (st.session_state.user_wins / total * 100) if total > 0 else 0
ai_win_rate = (st.session_state.ai_wins / total * 100) if total > 0 else 0
draw_rate = (st.session_state.draws / total * 100) if total > 0 else 0

col1, col2, col3 = st.columns(3)
with col1:
    st.metric("Games Played", st.session_state.total_games)
with col2:
    st.metric("Your Wins (O)", f"{st.session_state.user_wins} ({user_win_rate:.1f}%)")
with col3:
    st.metric("AI Wins (X)", f"{st.session_state.ai_wins} ({ai_win_rate:.1f}%)")

st.metric("Draws", f"{st.session_state.draws} ({draw_rate:.1f}%)")

if st.button("Reset Statistics", help="Clear all win/loss/draw counts"):
    st.session_state.total_games = 0
    st.session_state.user_wins = 0
    st.session_state.ai_wins = 0
    st.session_state.draws = 0
    st.session_state.game_outcome_recorded = False
    st.rerun()
